name: Build LaTeX PDF

on:
  push:
    branches: [ main, master ]
    paths:
      - '**'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build PDF with Docker
      run: |
        docker build -t latex-builder .
        docker run --rm -v $(pwd):/output latex-builder sh -c "cp main.pdf /output/"

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: main.pdf
        retention-days: 30

    - name: Check if PDF was created
      run: |
        if [ -f "main.pdf" ]; then
          echo "PDF successfully created"
          ls -la main.pdf
        else
          echo "PDF creation failed"
          exit 1
        fi